name: Build and Push Docker Image

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      
      - name: Checkout code
        uses: actions/checkout@v3

      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      
      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      
      - name: Build Docker image
        run: |
        docker build \
          --build-arg MONGODB_URI=${{ secrets.MONGODB_URI }} \
          -t your-dockerhub-username/my-nextjs-app:latest .
        docker push your-dockerhub-username/my-nextjs-app:latest

      
      - name: Push Docker image
        run: |
          docker tag your-dockerhub-username/my-nextjs-app:latest your-dockerhub-username/my-nextjs-app:latest
          docker push your-dockerhub-username/my-nextjs-app:latest
