name: Build and Push Docker Image

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      # Checkout the code from the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      # Log in to Docker Hub
      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      # Build Docker image and pass MONGODB_URI as a build argument
      - name: Build and Push Docker image
        run: |
          docker build \
            --build-arg MONGODB_URI=${{ secrets.MONGODB_URI }} \
            -t your-dockerhub-username/my-nextjs-app:latest .
          docker push your-dockerhub-username/my-nextjs-app:latest
